import logoUrl from '../../public/icon-app.png?inline';
import thisSource from './source-bundle.ts?raw';
import fredokaLicense from '@fontsource-variable/fredoka/LICENSE?raw';
import nunitoLicense from '@fontsource-variable/nunito/LICENSE?raw';
import { createSourceArchive, SOURCE_ZIP_NAME, type SourceEntry } from './source-archive.mjs';

// Raw imports are bundled text, not runtime requests to /src or /downloads.
// Keep the allowlist narrow so credentials, user data and generated ZIPs are never exported.
const sources = import.meta.glob<string>([
  '/src/**/*.{ts,tsx,mts,mjs,js,css}',
  '/scripts/*.mjs',
  '/tests/*.mjs',
  '/package.json',
  '/package-lock.json',
  '/tsconfig.json',
  '/vite.config.ts',
  '/postcss.config.mjs',
  '/index.html',
  '/README.md',
  '/PANDUAN-GITHUB.md',
  '/.gitignore',
  '/.gitattributes',
  '/.nvmrc',
  '/.github/workflows/deploy-pages.yml',
  '/public/.nojekyll',
  '/public/manifest.webmanifest',
  '/public/sw.js',
  '/public/recovery.html',
  '/public/_headers',
], { query: '?raw', import: 'default', eager: true });

export interface PreparedSource {
  blob: Blob;
  name: string;
  fileCount: number;
  size: number;
}

function assertActive(signal?: AbortSignal) {
  if (signal?.aborted) throw new DOMException('Penyediaan dibatalkan.', 'AbortError');
}

function decodeLogo() {
  const match = /^data:[^,]+;base64,([\s\S]+)$/.exec(logoUrl);
  if (!match) throw new Error('Imej sumber belum disertakan dalam aplikasi. Sila buka keluaran aplikasi terkini.');
  const decoded = atob(match[1]);
  return Uint8Array.from(decoded, (character) => character.charCodeAt(0));
}

async function createIcons(signal?: AbortSignal): Promise<SourceEntry[]> {
  const image = new Image();
  const logoBytes = decodeLogo();
  const decodedUrl = logoBytes[0] === 0xff && logoBytes[1] === 0xd8
    ? logoUrl.replace(/^data:[^;]+;/, 'data:image/jpeg;')
    : logoUrl;
  await new Promise<void>((resolve, reject) => {
    const timeout = window.setTimeout(() => reject(new Error('Imej sumber tidak dapat dibuka. Sila cuba lagi.')), 15_000);
    image.onload = () => { window.clearTimeout(timeout); resolve(); };
    image.onerror = () => { window.clearTimeout(timeout); reject(new Error('Imej sumber tidak dapat dibaca.')); };
    image.src = decodedUrl;
  });
  assertActive(signal);
  const specs: [string, number, number][] = [
    ['icon-192.png', 192, 0],
    ['icon-512.png', 512, 0],
    ['icon-maskable-512.png', 512, 112],
    ['apple-touch-icon.png', 180, 0],
  ];
  return Promise.all(specs.map(async ([name, size, padding]) => {
    const canvas = document.createElement('canvas');
    canvas.width = size;
    canvas.height = size;
    const context = canvas.getContext('2d');
    if (!context) throw new Error('Pelayar tidak dapat menyediakan ikon PWA.');
    context.fillStyle = '#ffffff';
    context.fillRect(0, 0, size, size);
    context.imageSmoothingQuality = 'high';
    const scale = (size - padding * 2) / Math.max(image.naturalWidth, image.naturalHeight);
    const width = image.naturalWidth * scale;
    const height = image.naturalHeight * scale;
    context.drawImage(image, (size - width) / 2, (size - height) / 2, width, height);
    const blob = await new Promise<Blob>((resolve, reject) => {
      canvas.toBlob((result) => result ? resolve(result) : reject(new Error('Ikon PWA tidak dapat dijana.')), 'image/png');
    });
    assertActive(signal);
    return { path: `public/icons/${name}`, content: new Uint8Array(await blob.arrayBuffer()) };
  }));
}

export function getBundledSourceEntries(): SourceEntry[] {
  const files = new Map(Object.entries(sources).map(([name, content]) => [name.replace(/^\//, ''), content]));
  // Vite excludes the importer itself from a glob. Export its raw text explicitly.
  files.set('src/pwa/source-bundle.ts', thisSource);
  files.set('licenses/fredoka-OFL.txt', fredokaLicense);
  files.set('licenses/nunito-OFL.txt', nunitoLicense);
  files.set('public/pwa-version.js', "// Regenerated by npm run build.\nself.__JOM_PWA_VERSION__ = 'github-source';\n");
  const entries: SourceEntry[] = [...files].map(([path, content]) => ({ path, content }));
  entries.push({ path: 'public/icon-app.png', content: decodeLogo() });
  return entries;
}

export async function prepareBundledSource(onProgress: (percent: number) => void, signal?: AbortSignal): Promise<PreparedSource> {
  assertActive(signal);
  onProgress(3);
  const entries = getBundledSourceEntries();
  entries.push(...await createIcons(signal));
  assertActive(signal);
  onProgress(15);
  const archive = await createSourceArchive(entries, (percent) => {
    assertActive(signal);
    onProgress(15 + Math.round(percent * 0.85));
  });
  assertActive(signal);
  return {
    name: SOURCE_ZIP_NAME,
    blob: new Blob([new Uint8Array(archive.bytes).buffer], { type: 'application/zip' }),
    fileCount: archive.fileCount,
    size: archive.size,
  };
}